# Basic parameters of the build
sudo: false
dist: bionic
group: edge
language: cpp
compiler: clang

# Blacklist - make sure we don't try to build gh-pages branch
branches:
  except:
    - gh-pages

# Install dependencies
addons:
  apt:
    packages:
      - libboost-all-dev
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - clang
      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - cmake
      - libglew-dev
      - libmpfr-dev
      - libglfw3-dev
      - qt5-default
      - qtdeclarative5-dev
      - libqt5opengl5-dev
      - libluabind-dev
      - libtbb-dev
      - libopencv-dev
      - libcgal-dev
      - libopenimageio-dev
      - libjsoncpp-dev
      - libeigen3-dev
      - libjemalloc-dev

env:
  global:
    - GH_REPO_NAME: possumwood
    - GH_REPO_REF: github.com/martin-pr/possumwood.git

stages:
- name: build
- name: docs
  if: branch = master

jobs:
  include:
  - stage: build
    script:
    - cd $TRAVIS_BUILD_DIR
    - ./tools/build-debug -j 4
    - ./tools/run-tests

  - stage: docs
    env:
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    script:
    - cd $TRAVIS_BUILD_DIR
    - ./tools/build-docs
